name: Run pipeline hello test bash
run-name: Hello Testbash
on: [push]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Unit Tests    
        run: cd ./src/webapp/api && npm install && npm run test
      - name: E2E
        run: cd ./e2e/cypress && npm install && npm run test  

