name: Run pipeline hello test bash
run-name: Hello Testbash
on: [push]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: "echo Hello Testbash"
      - name: run tests
        run: npm test

      
